<?php
/**
 * @file
 * Install, update and uninstall functions for the compro install profile.
 */

use Drupal\Core\Config\ConfigFactoryInterface;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function compro_install() {
  // Enable the admin theme.
  \Drupal::configFactory()->getEditable('node.settings')->set('use_admin_theme', '1')->save();
}
